"""Second

Revision ID: 542754e447a7
Revises: 6f478ed31ad0
Create Date: 2021-12-20 13:05:22.121556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542754e447a7'
down_revision = '6f478ed31ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
