"""Second2

Revision ID: e8518f3fd09b
Revises: 542754e447a7
Create Date: 2021-12-20 13:06:44.725161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8518f3fd09b'
down_revision = '542754e447a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
